server:
  port: 8085
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: nana
    username: root
    url: jdbc:mysql://127.0.0.1:3306/springsecurity
mybatis:
  mapper-locations: classpath:sqlmapper/*Mapper.xml