package com.example.springsecurity.dao;

import com.example.springsecurity.Pojo.PermissionRole;

public interface PermissionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int insert(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int insertSelective(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    PermissionRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PermissionRole record);
}