package com.example.springsecurity.Pojo;

public class PermissionRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_role.r_id
     *
     * @mbggenerated
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_role.permission_id
     *
     * @mbggenerated
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_role.id
     *
     * @return the value of permission_role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_role.id
     *
     * @param id the value for permission_role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_role.r_id
     *
     * @return the value of permission_role.r_id
     *
     * @mbggenerated
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_role.r_id
     *
     * @param rId the value for permission_role.r_id
     *
     * @mbggenerated
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_role.permission_id
     *
     * @return the value of permission_role.permission_id
     *
     * @mbggenerated
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_role.permission_id
     *
     * @param permissionId the value for permission_role.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}